/**
 * Arabic UI copy — single source of truth for dashboard chrome.
 * Glossary: docs/brainstorm/02-cms-dashboard.md §2.3
 */
export const copy = {
  // Product & shell
  appTitle: "غولدن كواليتي — إدارة محتوى الموقع",
  signIn: "تسجيل الدخول",
  signInSubtitle: "سجّل الدخول لتعديل محتوى الموقع",
  email: "البريد الإلكتروني",
  password: "كلمة المرور",
  signOut: "تسجيل الخروج",
  overview: "الرئيسية",
  overviewPrompt: "ماذا تريد أن تعدّل؟",

  // Sidebar groups & items
  nav: {
    websitePages: "صفحات الموقع",
    homePage: "الرئيسية",
    aboutPage: "من نحن",
    servicesPage: "صفحة الخدمات",
    projectsPage: "صفحة المشاريع",
    contactPage: "اتصل بنا",
    termsPage: "الشروط والسياسات",
    projects: "المشاريع",
    services: "الخدمات",
    media: "الصور والملفات",
    companySettings: "بيانات الشركة والإعدادات",
    siteLogo: "الشعار واسم الموقع",
    contactInfo: "الهاتف والبريد والعنوان",
    websiteMenu: "قائمة الموقع",
    socialLinks: "حسابات التواصل",
    ctaBand: "شريط تواصل معنا",
    seoAppearance: "مظهر البحث في جوجل",
  },

  // Common actions & status
  save: "حفظ",
  saving: "جاري الحفظ…",
  saved: "تم الحفظ",
  cancel: "إلغاء",
  delete: "حذف",
  confirmDelete: "هل أنت متأكد من الحذف؟ لا يمكن التراجع بسهولة.",
  addPhoto: "إضافة صورة",
  changePhoto: "تغيير الصورة",
  removePhoto: "إزالة الصورة",
  addProject: "إضافة مشروع",
  addService: "إضافة خدمة",
  edit: "تعديل",
  viewOnWebsite: "عرض في الموقع",
  showOnWebsite: "إظهار في الموقع",
  hideFromWebsite: "إخفاء من الموقع",
  statusVisible: "ظاهر في الموقع",
  statusHidden: "مخفي",
  showOnHome: "إظهار في الصفحة الرئيسية",
  badgeOnHome: "في الرئيسية",
  mainPhoto: "الصورة الرئيسية",
  photos: "الصور",
  basics: "الأساسيات",
  description: "الوصف",
  moreOptions: "المزيد من الخيارات",
  pageSlug: "رابط الصفحة",
  pageSlugHelp: "يُستخدم في عنوان الصفحة على الإنترنت. يُملأ تلقائياً من الاسم.",
  localeAr: "العربية",
  localeEn: "English",
  photoOnLeft: "الصورة على اليسار",
  photoOnRight: "الصورة على اليمين",
  editServicesList: "تعديل قائمة الخدمات",
  editProjectsList: "تعديل قائمة المشاريع",
  photoAlt: "وصف قصير للصورة",
  richText: "نص منسّق",

  // Revalidate
  updateWebsite: "تحديث الموقع الآن",
  updateWebsiteHelp:
    "بعد الانتهاء من التعديل والحفظ، اضغط هنا ليظهر الزوار آخر التغييرات على الموقع.",
  updateWebsiteSuccess:
    "تم تحديث الموقع. يمكنك الآن مراجعة الصفحات على الموقع.",
  updateWebsiteFailure:
    "تم الحفظ هنا، لكن الموقع العام لم يتحدّث. حاول مرة أخرى أو تواصل مع الدعم.",
  updating: "جاري التحديث…",
  loading: "جاري التحميل…",
  uploadingPhoto: "جاري رفع الصورة…",

  // Empty states & errors
  noProjects: "لا توجد مشاريع بعد. أضف أول مشروع.",
  saveFailed: "تعذّر الحفظ. تحقق من الاتصال بالإنترنت ثم حاول مرة أخرى.",
  missingMainPhoto:
    "يرجى إضافة صورة رئيسية قبل إظهار هذا المحتوى في الموقع.",
  wrongLogin: "البريد الإلكتروني أو كلمة المرور غير صحيحة.",
  sessionExpired: "انتهت جلسة الدخول. سجّل الدخول مرة أخرى.",
  connectionFailed:
    "تعذّر الاتصال بالخادم. تحقق من الإنترنت أو أن واجهة البرمجة تعمل ثم حاول مرة أخرى.",
  signingIn: "جاري تسجيل الدخول…",
  emailRequired: "يرجى إدخال البريد الإلكتروني.",
  passwordRequired: "يرجى إدخال كلمة المرور.",
  unsavedChanges: "لديك تغييرات غير محفوظة. هل تريد المغادرة دون حفظ؟",
  unsavedHint: "لديك تغييرات غير محفوظة",
  featuredWarning:
    "الصفحة الرئيسية تعرض عادةً حتى ٣ مشاريع. يمكنك المتابعة، لكن قد يظهر عدد أكبر من المعتاد.",

  // Overview shortcuts (placeholders)
  shortcutEditHome: "تعديل الصفحة الرئيسية",
  shortcutAddProject: "إضافة مشروع",
  shortcutChangePhone: "تغيير رقم الهاتف",
  projectsSummary: "ملخص المشاريع",
  projectsVisibleCount: "{count} مشروعاً ظاهراً",
  projectsHiddenCount: "{count} مخفي",
  projectsFeaturedCount: "{count} في الرئيسية",
  projectsLoadFailed: "تعذّر تحميل ملخص المشاريع.",
  viewAllProjects: "عرض كل المشاريع",

  // Placeholders & empty
  placeholderHint:
    "هذه الشاشة قيد التجهيز. يمكنك التنقّل من القائمة الجانبية.",
  pageEditorComingSoon: "ستُربط هذه الصفحة بالحفظ وواجهة البرمجة لاحقاً.",
  settingsComingSoon: "ستُحفظ هذه الإعدادات عبر واجهة البرمجة في مرحلة لاحقة.",
  noServicesYet:
    "لا توجد خدمات معروضة بعد. ستظهر الخدمات الثلاث هنا بعد ربط واجهة البرمجة.",
  noServicesMatch: "لا توجد خدمات تطابق البحث.",
  serviceCardTab: "بطاقة صفحة الخدمات",
  serviceDetailTab: "صفحة الخدمة الكاملة",
  serviceName: "اسم الخدمة",
  serviceDetailsList: "نقاط البطاقة",
  serviceAddDetail: "إضافة نقطة",
  serviceIntroduction: "المقدمة",
  serviceScope: "نطاق العمل",
  serviceAddScope: "إضافة بند نطاق",
  serviceScopeTitle: "عنوان البند",
  serviceScopeDescription: "وصف البند",
  serviceStandards: "المعايير",
  serviceMethodology: "كيف نعمل",
  serviceAddStep: "إضافة خطوة",
  serviceStep: "خطوة",
  serviceBanner: "صورة البانر",
  serviceCardImage: "صورة البطاقة",
  serviceMetaTitle: "عنوان البحث",
  serviceMetaDescription: "وصف البحث",
  noMediaYet: "لا توجد صور بعد. ارفع أول صورة من هنا لاحقاً.",
  projectName: "اسم المشروع",
  projectNamePlaceholder: "مثال: تجهيز مختبر النفط والغاز",
  projectNameHelp: "سيظهر هذا الاسم في قائمة المشاريع وعلى الموقع.",
  projectClient: "العميل",
  projectLocation: "الموقع",
  projectYear: "السنة",
  projectPhotos: "الصور",
  projectPhotosHelp:
    "أضف معرّفات الصور مؤقتاً. رفع الصور وترتيبها سيُتاح بالكامل في الخطوة التالية.",
  projectPhotoId: "معرّف صورة",
  addPhotoId: "إضافة صورة أخرى",
  projectBasics: "البيانات الأساسية",
  projectCreatedHidden: "تم الحفظ كمشروع مخفي. يمكنك إظهاره في الموقع عند الجاهزية.",
  projectEditComingSoon: "تعديل المشروع بالكامل قادم في المرحلة التالية.",
  filterAll: "الكل",
  searchProjects: "ابحث باسم المشروع",
  searchServices: "ابحث باسم الخدمة",
  noProjectsMatch: "لا توجد مشاريع تطابق البحث أو التصفية.",
  descriptionHelp: "يمكنك إضافة التفاصيل لاحقاً.",
  titleRequired: "يرجى إدخال اسم المشروع.",
  slugRequired: "يرجى إدخال رابط الصفحة.",
  slugInvalid: "رابط الصفحة يجب أن يكون بأحرف إنجليزية صغيرة وأرقام وشرطات فقط.",
  slugTaken: "هذا الرابط مستخدم لمشروع آخر. غيّره من المزيد من الخيارات.",
  toggleVisibility: "تغيير الظهور",
  showingOnWebsite: "جاري الإظهار…",
  hidingFromWebsite: "جاري الإخفاء…",
  contentStatus: "حالة المحتوى",
  emptyDefault: "لا يوجد محتوى لعرضه هنا بعد.",
  confirm: "تأكيد",
  close: "إغلاق",
  contentLanguage: "لغة المحتوى",
} as const;

export type Copy = typeof copy;
