/**
 * Field labels + help text for page editors (Arabic).
 */
export const fields = {
  seo: {
    title: "عنوان الصفحة",
    metaTitle: "عنوان البحث في جوجل",
    metaTitleHelp: "يظهر كعنوان للنتيجة في محركات البحث.",
    description: "وصف البحث في جوجل",
    descriptionHelp: "جملة قصيرة تظهر تحت العنوان في نتائج البحث.",
    image: "صورة المشاركة",
    imageHelp: "صورة اختيارية عند مشاركة الرابط.",
    draft: "إخفاء هذه الصفحة من الموقع",
  },
  banner: {
    title: "العنوان الكبير",
    subtitle: "النص القصير تحت العنوان",
    image: "صورة أعلى الصفحة",
    imageHelp: "هذه الصورة تظهر في أعلى الصفحة الرئيسية.",
    button1Label: "نص الزر الأول",
    button1Href: "رابط الزر الأول",
    button2Label: "نص الزر الثاني",
    button2Href: "رابط الزر الثاني",
  },
  features: {
    subTitle: "عنوان فرعي",
    title: "عنوان القسم",
    description: "وصف القسم",
    listTitle: "عناصر القائمة",
    itemTitle: "العنوان",
    itemContent: "النص",
    addItem: "إضافة عنصر",
  },
  whyChooseUs: {
    subTitle: "عنوان فرعي",
    title: "عنوان القسم",
    listTitle: "النقاط",
    addLine: "إضافة سطر",
    line: "نقطة",
  },
  featuredProjects: {
    subTitle: "عنوان فرعي",
    title: "عنوان القسم",
    viewAll: "نص زر عرض الكل",
  },
  aboutUs: {
    subtitle: "عنوان فرعي",
    title: "العنوان",
    content: "النص",
    image: "صورة القسم",
    imageHelp: "تظهر بجانب نص «من نحن».",
  },
  visionMission: {
    subtitle: "عنوان فرعي",
    content: "النص",
  },
  values: {
    subtitle: "عنوان فرعي",
    title: "عنوان القسم",
    listTitle: "القيم",
    itemLabel: "الاسم",
    itemDescription: "الوصف",
    addItem: "إضافة قيمة",
  },
  sectors: {
    enable: "إظهار قسم القطاعات",
    subtitle: "عنوان فرعي",
    title: "عنوان القسم",
    listTitle: "القطاعات",
    itemLabel: "اسم القطاع",
    itemDescription: "الوصف",
    addItem: "إضافة قطاع",
  },
  servicesUi: {
    knowMore: "نص زر «اعرف المزيد»",
    close: "نص زر الإغلاق",
  },
  projectsIntro: {
    intro: "مقدمة صفحة المشاريع",
    introHelp: "النص الظاهر أعلى قائمة المشاريع.",
  },
  contactIntro: {
    intro: "مقدمة صفحة التواصل",
  },
  contactForm: {
    heading: "عنوان النموذج",
    name: "تسمية الاسم",
    namePlaceholder: "Placeholder للاسم",
    email: "تسمية البريد",
    emailPlaceholder: "Placeholder للبريد",
    phone: "تسمية الهاتف",
    phonePlaceholder: "Placeholder للهاتف",
    subject: "تسمية الموضوع",
    message: "تسمية الرسالة",
    submit: "نص زر الإرسال",
    sending: "نص أثناء الإرسال",
    success: "رسالة النجاح",
    error: "رسالة الخطأ",
    successTitle: "عنوان رسالة النجاح",
    errorTitle: "عنوان رسالة الخطأ",
    modalOk: "نص زر حسناً",
    help: "هذه تسميات الحقول فقط. رقم الهاتف والبريد يُعدَّلان من بيانات الشركة.",
  },
  businessHours: {
    enable: "إظهار ساعات العمل",
    title: "عنوان ساعات العمل",
    hours: "نص الساعات",
  },
  terms: {
    content: "محتوى الشروط والسياسات",
  },
  iconLabel: "الأيقونة",
  mediaIdPlaceholder: "معرّف الصورة (مؤقتاً حتى مكتبة الصور)",
  noImageYet: "لا توجد صورة",
  pageLinkPlaceholder: "اختر صفحة من الموقع",
  pageLinkCustom: "رابط مخصص…",
  pageLinkCustomPlaceholder: "/path أو https://…",
  richTextHelp: "استخدم شريط الأدوات للخط العريض والقوائم.",
  richBold: "عريض",
  richBulletList: "قائمة",
  richOrderedList: "ترقيم",
  tagPlaceholder: "أضف وسم خدمة ثم Enter",
  addTag: "إضافة وسم",
  serviceTags: "وسوم الخدمات",
  serviceTagsHelp: "كلمات قصيرة تربط المشروع بالخدمات ذات الصلة.",
  setMainPhoto: "تعيين كصورة رئيسية",
  photoAltPanel: "وصف الصورة",
  galleryEmpty: "لا توجد صور بعد. ارفع صوراً لهذا المشروع.",
  projectSeoHelp:
    "عنوان المشروع يظهر في نتائج البحث. يمكنك تعديل رابط الصفحة هنا.",
  sectionsHeading: "أقسام الصفحة",
  selectSection: "اختر قسماً للتعديل",
  editServicesListHint: "لإدارة بطاقات الخدمات وصفحاتها التفصيلية.",
  editProjectsListHint: "لإدارة المشاريع وصورها.",
} as const;
